name: Test if scripts work as expected

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            reset-environment: powershell .\reset.ps1
            install: powershell .\install.ps1
          - os: windows-latest
            reset-environment: powershell .\reset.ps1
            install: powershell .\install.ps1
          - os: macos-13
            reset-environment: bash ./reset.sh
            install: bash ./install.sh
          - os: macos-latest
            reset-environment: bash ./reset.sh
            install: bash ./install.sh
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Reset runner environment
        run: ${{ matrix.reset-environment }}
      
      - name: Execute the installer
        run: ${{ matrix.install }}

      - name: Check Appium
        run: appium --version
      
      - name: Check Java
        run: java -version
      
      - name: Check Android SDK manager
        run: sdkmanager --list

      - name: Check Android virtual device
        run: avdmanager list device
      
      - name: Check Python
        run: python --version
