name: Test if scripts work as expected

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            reset-script: powershell .\reset.ps1
            install-script: powershell .\install.ps1
            verify-script: powershell .\verify.ps1
          - os: windows-latest
            reset-script: powershell .\reset.ps1
            install-script: powershell .\install.ps1
            verify-script: powershell .\verify.ps1
          - os: macos-13
            reset-script: bash ./reset.sh
            install-script: bash ./install.sh
            verify-script: bash ./verify.sh
          - os: macos-latest
            reset-script: bash ./reset.sh
            install-script: bash ./install.sh
            verify-script: bash ./verify.sh
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Reset runner environment
        run: ${{ matrix.reset-script }}
      - name: Execute the installer
        run: ${{ matrix.install-script }}
      - name: Verify installation
        run: ${{ matrix.verify-script }}
