name: Test if scripts work as expected

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
        matrix:
          include:
            - os: windows-latest
              script: powershell .\install.ps1
            - os: macos-latest
              script: bash ./install.sh
            # because these runners come with preinstalled tools,
            # we better test also on bare system images:
            # - mcr.microsoft.com/windows/nanoserver:ltsc2022
            # - sickcodes/docker-osx:latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - run: ${{ matrix.script }}
      
      - name: Check Appium
        run: appium --version
      
      - name: Check Java
        run: java -version
      
      - name: Check Android virtual device
        run: avdmanager move avd --name 'Appium'
      
      - name: Check Python
        run: python --version
